# Generated by Django 4.1 on 2022-10-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imageupload_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
